### ISSUE TITLE
PopUp Layout 

### ISSUE THREAD

**Issue by smn57** [smn57/frag.extract.a#11]
Discussion about the layout of the Chrome extension.
Two possibilities shown below:
![Auswahl_157](https://user-images.githubusercontent.com/34234300/63152570-72d1bf80-c00c-11e9-9c08-ebe5bca771a6.png)
![Auswahl_156](https://user-images.githubusercontent.com/34234300/63152571-72d1bf80-c00c-11e9-81fa-6e893f1faa72.png)

**Comment by smn57** [comment]
![Auswahl_158](https://user-images.githubusercontent.com/34234300/63153321-546cc380-c00e-11e9-86a6-e0f5e1203452.png)

**Comment by tneuschaefer** [comment]
We have selected the layout proposed in the comment. While it is not ideal to have the description and the codeblock all the way at the bottom, the scroll button must be next to the codeblock, therefore the codeblock must be at the bottom to not waste space. It is then only logical to have the description next to the codeblock, also near the bottom of the popup
