### ISSUE TITLE
Click on "Save" not saving fragment to database, just closing popup

### ISSUE THREAD

**Issue by tneuschaefer** [smn57/frag.extract.a#4]
Sometimes when "Save " is clicked, the popup closes but the fragment is not saved to the database and the state is not cleared. So when you reopen the popup, all the changes you've made are still there.

This has occurred multiple times, but there is no discernible pattern when this behaviour happens.

Possible explanation: window.close() is executed before the message is send to the background script (which executes the save functionality) and then the message gets canceled

Possible solution: move window.close() in the response function of sendMessage, which should only be executed after the message has been send

**Comment by tneuschaefer** [comment]
Implemented possible solution in dev branch.
Will look out if bug appears again.

**Comment by smn57** [comment]
Bug does not occur on linux. Saving closes popup and saves.

**Comment by tneuschaefer** [comment]
No further occurence noted since possible solution was implemended; closing this issue
