### ISSUE TITLE
Jump-to from Pop-up jumps to bottom of fragment

### ISSUE THREAD

**Issue by smn57** [smn57/frag.extract.a#7]
Clicking the Jump-to button scrolls up/down to the desired codeblock, but the view top is lined up with the blocks bottom.

**Comment by smn57** [comment]
Changed scroll position from `ỳ` to `top` and removed the subtraction. Seems to work now on a couple of websites.

**Comment by tneuschaefer** [comment]
Currently the jump to button is completely inoperable, due to the way that the codeblock is selected. After the selection process the program has currently no way to get the DOM element, where that selected codeblock originally came from, which it needs to set the scroll position

**Comment by tneuschaefer** [comment]
Jump to button now works again, the position the page scrolls to is still wrong and inconsistent. Needs further testing!

**Comment by tneuschaefer** [comment]
changed scroll method to using Element.scrollIntoView(). That fixed it.
