### ISSUE TITLE
Sending empty Fragments

### ISSUE THREAD

**Issue by smn57** [smn57/frag.extract.a#9]
It's possible to send empty fragments if they have a label. This can happen when there is no answer with a codeblock (yet) in a threat.

**Comment by smn57** [comment]
Solution might be to set the "code" on mandatory as well as the label is.

**Comment by tneuschaefer** [comment]
A user might find a question without any (suitable) answer, but manages to solve their problem in their project anyways and then decides that they want to create a fragment of it. To save time having to fill all the attributes manually the user might want to use the chrome extension to create an emtpy fragment, save it and then fill in the codeblock with the code they copied from their project in frag edit's vsc extension.

This scenario is quite far fetched, so it might be alright to set "code" as required.

**Comment by tneuschaefer** [comment]
Also made language a requirement.
